server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marssvn?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  messages:
    basename: i18n/messages, i18n/validations
    encoding: UTF-8

mybatis:
  mapper-locations: mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
