server:
  port: 8090

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marssvn?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      filters: slf4j
      filter:
        slf4j:
          enabled: true
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
  messages:
    basename: i18n/messages, i18n/validations
    encoding: UTF-8
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

mybatis:
  mapper-locations: mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
#  path: ./logs
  level:
    org.apache.coyote.http11.Http11InputBuffer: debug
    druid.sql.Statement: debug

